
export default {

	CURRENT_USER_RECEIVED: 	'CURRENT_USER_RECEIVED',
	PERSONAL_INFO_RECEIVED: 'PERSONAL_INFO_RECEIVED',
  PERSONAL_STATEMENT_RECEIVED: 'PERSONAL_STATEMENT_RECEIVED',
	UNIVERSITY_RECEIVED: 'UNIVERSITY_RECEIVED'
}
