
export default {

	CURRENT_USER_RECEIVED: 	'CURRENT_USER_RECEIVED',
	PERSONAL_INFO_RECEIVED: 'PERSONAL_INFO_RECEIVED',
  PERSONAL_STATEMENT_RECEIVED: 'PERSONAL_STATEMENT_RECEIVED',

  //Searched University actions
  SEARCHED_UNIVERSITY_RECEIVED: 'SEARCHED_UNIVERSITY_RECEIVED',

  //Selected Universities actions
	SELECTED_UNIVERSITIES_RECEIVED: 'SELECTED_UNIVERSITIES_RECEIVED',
	REMOVE_SELECTED_UNIVERSITY: 'REMOVE_SELECTED_UNIVERSITY',

	// Saved Universities actions
	REMOVE_SAVED_UNIVERSITY: 'REMOVE_SAVED_UNIVERSITY',
	ADD_SAVED_UNIVERSITY: 'ADD_SAVED_UNIVERSITY',
	SAVED_UNIVERSITIES_RECEIVED: 'SAVED_UNIVERSITIES_RECEIVED',

	//Profile actions
	PROFILE_PICTURE_URL_RECEIVED: 'PROFILE_PICTURE_URL_RECEIVED',
}
